### PR TITLE
Use fetch and checkout origin/main instead of pull

### LINKED ISSUE #147: Crash when trying to sync with main branch that have diff history
Handel the error:
 ⨯ Error: Need to specify how to reconcile divergent branches.
    at new Promise (<anonymous>)
    at Generator.next (<anonymous>)

## Description
In case the local repo main branch have a divergent history than main in the remote the app crash at first requires as it fail to "git pull"

Suggestion: Always to force and rebase with git pull from main, in other words to accept remote as is. Or basically always checkout the new branch from origin/main, in this case we only need to git fetch then checkout new branch from origin/main. Remember to read the main branch name from project config `base_branch`

### PR DESCRIPTION
**Pull request by amerharb**
## Description
Solve the issue if main brach in local have diff history than remote one.

## Changes
- instead of (checkout main then pull) now we (fetch then checkout origin/main) 

## Related issues
Resolves #147

### CODE REVIEW

File: webapp/src/RepoGit.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ import { getTranslationsBySourceFile } from '@/utils/translationObjectUtil';
 import { Store } from '@/store/Store';
 
 export class RepoGit {
+  private MIN_TIME_TO_FETCH = 30_000; // 30 sec before fetch again
```
Comment (amerharb) [inline webapp/src/RepoGit.ts:20]: is this var name clear ?

Comment (WULCAN) [reply webapp/src/RepoGit.ts:20]: MIN_TIME_TO_FETCH as an abbreviation of minimum time to fetch is not very clear. Time can refer to either a point in time, or a duration. A minimum point in time would be the earliest possible time for a fetch, and a minimum duration would be the smallest duration for a fetch, or the smallest duration between fetches. This constant is neither of those.

The constant is instead used to determine if the cached data for the remote is still valid or if the remote should be queried again with a fetch. A common term used with this kind of cache invalidation is time to live, and our constant would then be the maximum or initial time to live. Another common term for this is maximum age.

https://en.wikipedia.org/wiki/Time_to_live

Comment (amerharb) [reply webapp/src/RepoGit.ts:20]: I will change it to GIT_FETCH_TTL

File: webapp/src/RepoGit.ts [hunk 2]
```diff
@@ -58,26 +59,25 @@ export class RepoGit {
...
-    await git.checkout(spConfig.baseBranch);
-    debug(`Checked out base branch: ${spConfig.baseBranch}`);
+    debug(`Checkout base branch: ${spConfig.originBaseBranch} ...`);
+    await git.checkout(spConfig.originBaseBranch);
+    debug(`Checked out base branch: ${spConfig.originBaseBranch}`);
   }
 
   /**
    * Checkout base branch and pull
    * @returns base branch name
```
Comment (xela1601) [inline webapp/src/RepoGit.ts:69]: you need to adjust the doc comment here as well, right? :)

**Review by henrycatalinismith — DISMISSED** [review]
seems bloody important

**Review by henrycatalinismith — APPROVED** [review]
